### ISSUE TITLE
Menu button is overlapping on the name

### ISSUE THREAD

**Issue by suryagowda** [suryagowda/sugo.me#1]
When u visit my website in "mobile",the menu button is overlapping on the name ...only when website is open in mobile...This is a good first issue for biginners in html,css...try it

**Comment by nazneenshaikh-db** [comment]
check the pull request

**Comment by suryagowda** [comment]
Can you please send the pull request again.Because I accidentally reverted your pull request after merging.

**Comment by SeanIsHerko** [comment]
Hi, Are you still looking for help with this? 

Thanks,
Sean
